userAgent: 'WhatsApp/2.2037.6 Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.83 Safari/537.36'
# number phone for owner to able use another feature
ownerNumber: '6289696133160@c.us'
path:
  chrome: 'C:\\Program Files\\Google\\Chrome\\Application\\chrome.exe'
  # jangan dihapus ini folder, media dan json berisi file-file penting
  media: './storage/media'
  json: './storage/json'
  log: './storage/log'
  # terserah mau dihapus atau tidak, karena menyimpan hasil downlaod
  tempMedia: './storage/temp-media'
  instagram: './storage/temp-media/instagram'
  youtube: './storage/temp-media/youtube'